spring.application.name=TechTitans

# Database Connection
spring.datasource.url=jdbc:h2:mem:proxydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate/JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable the H2 Web Console (Crucial for debugging!)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
