spring.application.name=TechTitans

spring.datasource.url=jdbc:h2:mem:proxydb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.datasource.hikari.maximum-pool-size=15

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console